//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.22 at 09:17:12 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://debit.com/copybook/trans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.debit.copybook.trans;
